/**
 * Tinker Plan Template
 *
 * The markdown template structure for work plans generated by Tinker.
 * Includes TL;DR, context, objectives, verification strategy, TODOs, and success criteria.
 */

export const PROMETHEUS_PLAN_TEMPLATE = `## Plan Structure

Generate plan to: \.specify/plans/{name}.md

\`\`\`markdown
# {Plan Title}

## TL;DR

> **Quick Summary**: [1-2 sentences: core objective + approach]
> **Deliverables**:
> - [Output 1]
> - [Output 2]
> **Estimated Effort**: [Quick | Short | Medium | Large | XL]
> **Parallel Execution**: [YES - N waves | NO - sequential]
> **Critical Path**: [Task X -> Task Y -> Task Z]

---

## Context

### Original Request
[User's initial description]

### Interview Summary
- Decisions: [Key choice + rationale]
- Findings: [Research or constraints]

### Rubick Review (if any)
- Gaps addressed: [Gap -> Resolution]

---

## Work Objectives

### Core Objective
[1-2 sentences: what we are achieving]

### Concrete Deliverables
- [Exact file/endpoint/feature]

### Definition of Done
- [ ] [Verifiable condition with command]

### Must Have
- [Non-negotiable requirement]

### Must NOT Have
- [Explicit exclusion / scope boundary]

---

## Verification Strategy (MANDATORY)

**ZERO HUMAN INTERVENTION.** Every task must be verifiable by the agent using tools/commands.
**FORBIDDEN**: "user manually tests", "user visually confirms", "ask user to verify".

### Test Decision
- Infrastructure exists: [YES/NO]
- Automated tests: [TDD / Tests-after / None]
- Framework: [bun test / vitest / jest / pytest / none]

### If TDD
Each TODO follows RED -> GREEN -> REFACTOR with \`bun test [file]\`.

### Agent-Executed QA Scenarios (MANDATORY - ALL tasks)
Provide at least one happy-path and one negative scenario per feature.

Format:
\`\`\`
Scenario: [Descriptive name]
  Tool: [Playwright | interactive_bash | Bash]
  Preconditions: [What must be true]
  Steps:
    1. [Exact action]
    2. [Next action]
    3. [Assertion]
  Expected Result: [Concrete outcome]
  Failure Indicators: [What indicates failure]
  Evidence: [.specify/evidence/...]
\`\`\`

---

## Execution Strategy

### Parallel Execution Waves
- Wave 1: [Tasks]
- Wave 2: [Tasks]
- Wave 3: [Tasks]
Critical Path: [Task X -> Task Y -> Task Z]

### Dependency Matrix
| Task | Depends On | Blocks | Can Parallelize With |
|------|------------|--------|---------------------|
| 1 | None | 2 | 3 |

### Agent Dispatch Summary
| Wave | Tasks | Recommended Agents |
|------|-------|-------------------|
| 1 | 1, 2 | task(category="...", load_skills=[...], run_in_background=false) |

---

## TODOs

> Implementation + Test = ONE task. Each task includes agent profile + parallelization.

- [ ] 1. [Task Title]

  **What to do**
  - [Clear implementation steps]
  - [Test cases to cover]

  **Must NOT do**
  - [Specific exclusions]

  **Recommended Agent Profile**
  - Category: \`visual-engineering | ultrabrain | artistry | quick | unspecified-low | unspecified-high | writing\`
  - Skills: [\`skill-1\`, \`skill-2\`] (why each)
  - Skills omitted: [\`skill-x\`] (why)

  **Parallelization**
  - Can Run In Parallel: YES | NO
  - Parallel Group: Wave N | Sequential
  - Blocks: [Tasks that depend on this]
  - Blocked By: [Tasks this depends on] | None

  **References** (be exhaustive; explain why)
  - Pattern: \`path:line\` -> [why]
  - API/Type: \`path:Type\` -> [why]
  - Tests: \`path:test\` -> [why]
  - Docs: \`path#section\` -> [why]
  - External: \`https://...\` -> [why]

  **Acceptance Criteria**
  - [ ] Agent-executable checks only
  - [ ] If tests: \`bun test ...\` -> PASS
  - [ ] QA scenarios listed above

  **Commit**: YES | NO
  - Message: \`type(scope): desc\`
  - Files: \`path/to/file\`
  - Pre-commit: \`test command\`

---

## Commit Strategy

| After Task | Message | Files | Verification |
|------------|---------|-------|--------------|
| 1 | \`type(scope): desc\` | file.ts | bun test |

---

## Success Criteria

### Verification Commands
\`\`\`bash
command  # Expected: output
\`\`\`

### Final Checklist
- [ ] Must Haves present
- [ ] Must NOT Haves absent
- [ ] All tests pass
\`\`\`

---
`
